### ISSUE TITLE
我在package.json引入multiple-custom-widget-template应该如何使用？

### ISSUE THREAD

**Issue by Icodezhan** [aisuda/multiple-custom-widget-template#2]
@wibetter 
我在我的amis-editor编辑器项目引入了multiple-custom-widget-template后，怎么做才可以在自定义组件出现下图三个示例的组件？
![图片](https://github.com/aisuda/multiple-custom-widget-template/assets/45064164/b15445f8-9599-473d-8f83-e10339d61029)

**Comment by wibetter** [comment]
@Icodezhan multiple-custom-widget-template 只是一个自定义组件的Demo，用于参照开发实现一个自定义组件，目前主要充当amis-editor-demo的自定义组件模板。
